### ISSUE TITLE
multiple profiles for different projects?

### ISSUE THREAD

**Issue by giovp** [Snakemake-Profiles/slurm#51] opened 2020-06-30 10:30 UTC
Hi,

I'd like to finally move to using profiles. However, I'm still not sure how to adapt the profiles workflow with having several different pipelines. I see 3 ways:
- have different slurm profiles for different projects (e.g. slurm_proj1, slurm_proj2 etc. ) but this doesn't seem to be possible
- set up profiles in specific project folders (also seems to not be possible)
- set up one slurm profile in `~/.config/snakemake` and then use project specifics `cluster_configs` files, which seem to be possible (?), but then again since it uses cluster_configs files, it seems to defeat the purpose?

I'm clearly missing something important, but bottom line I would like to set some default resources in the slurm profile and then adapt to different pipelines/cluster specs etc. in each specific project. Also, when you share a snakemake pipeline with the public, how do you "attach" the (default) slurm profile in the public pipeline repo?

Thank you!

Giovanni

**Comment by frankier** [comment] 2020-07-10 05:33
I agree the profile mechanism is a bit confusing. For me, having config that lives in a user's directory like this seems to run counter counter to the aim of reproducibility. However let me quote:

```
  --profile PROFILE     Name of profile to use for configuring Snakemake.
                        Snakemake will search for a corresponding folder in
                        /etc/xdg/snakemake and
                        /home/frankier/.config/snakemake. Alternatively, this
                        can be an absolute or relative path. The profile
                        folder has to contain a file 'config.yaml'. This file
                        can be used to set default values for command line
                        options in YAML format. For example, '--cluster qsub'
                        becomes 'cluster: qsub' in the YAML file. Profiles can
                        be obtained from https://github.com/snakemake-
                        profiles. (default: None)
```

So you can just specify a path to a profile, which is what I would recommend. This way you can distribute a "known working" profile, that anyone can either use directly, or as a reference point for running in a different environment.

That said, I think of this repository more as library code rather than configuration and have used cluster configs for actually specifying the desired resources.

**Comment by giovp** [comment] 2020-07-10 06:52
Agree, and that's what I ended up doing: creating a profile folder in the project directory, with inside two config files (snakemake and cluster). It clearly is a hack and defies the original purpose, but works well for me!

**Comment by percyfal** [comment] 2020-09-14 11:13
Hi, sorry for the delay in responding to this. @giovp can I close this issue for now? The way I use it depends on the project, but most of the time, I put the profile in the project directory itself such that it would be accessible to collaborators. Since cluster configuration is deprecated (https://snakemake.readthedocs.io/en/stable/snakefiles/configuration.html#cluster-configuration-deprecated), the profile would need additional functionality similar to that in https://github.com/Snakemake-Profiles/lsf. And yes, I would regard the library more as library code than configuration, a template for modification if you will.

**Comment by zihhuafang** [comment] 2021-02-03 11:27
Hi @percyfal,  
I am currently experiencing issue when providing the absolute path with my profile that is located in the project directory.

I ran my snakemake command as follow:
`snakemake --profile /mnt/gluster/bio-informatik/fangz/test_aln/fangz_profile -rp`

I got the following error message showing that snakemake was still looking for cluster_config.yml in my home directory.

`Traceback (most recent call last):
  File "/mnt/gluster/bio-informatik/fangz/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/io.py", line 1564, in _load_configfile
    with open(configpath) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/fangz/.config/snakemake/fangz_profile/cluster_config.yml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/gluster/bio-informatik/fangz/test_aln/fangz_profile/slurm-submit.py", line 33, in <module>
    cluster_config = slurm_utils.load_cluster_config(CLUSTER_CONFIG)
  File "/mnt/gluster/bio-informatik/fangz/test_aln/fangz_profile/slurm_utils.py", line 49, in load_cluster_config
    dcc = io.load_configfile(path)
  File "/mnt/gluster/bio-informatik/fangz/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/io.py", line 1594, in load_configfile
    config = _load_configfile(configpath)
  File "/mnt/gluster/bio-informatik/fangz/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/io.py", line 1589, in _load_configfile
    raise WorkflowError("{} file {} not found.".format(filetype, configpath))
snakemake.exceptions.WorkflowError: Config file /home/fangz/.config/snakemake/fangz_profile/cluster_config.yml not found.`

I am not sure why given the absolut path of profile did not work.
Could you please advise me how to fix it?

Thanks in advacne.
Best wishes,
Zih-Hua

**Comment by percyfal** [comment] 2021-02-08 20:01
Hi @zihhuafang, 

what does your config.yaml file for that profile look like? The path to the cluster configuration file is set relative to the profile dir, unless given as an absolute path in config.yaml.

**Comment by zihhuafang** [comment] 2021-03-03 07:24
Hi @percyfal,
Thanks for the reply.
I did not specify the path of cluster configuration file in my `config.yml`.
So it's indeed set relative to my profile dir, of which I provided the absolute path to `--profile`.
I ended up in putting the absolute path of `cluster_config.yml` in `slurm-submit.py` to fix this problem.

**Comment by percyfal** [comment] 2022-02-15 19:40
@zihhuafang closing this issue. Feel free to reopen if you need more input.

**Closed by percyfal** 2022-02-15 19:40 UTC
